-- Schema definition for HR Employee Data
CREATE TABLE hr_employee_data (
    Employee_ID VARCHAR(50) PRIMARY KEY,
    Employee_Name VARCHAR(255),
    Gender VARCHAR(50),
    Age INT,
    Department VARCHAR(100),
    Job_Role VARCHAR(100),
    Job_Level INT,
    Education VARCHAR(100),
    Years_At_Company DECIMAL(5,2),
    Total_Work_Experience DECIMAL(5,2),
    Salary DECIMAL(15,2),
    Salary_Band VARCHAR(50),
    Overtime VARCHAR(10),
    Work_Life_Balance INT,
    Job_Satisfaction INT,
    Environment_Satisfaction INT,
    Performance_Rating INT,
    Training_Hours INT,
    Promotion_Last_Year INT,
    Manager_Tenure DECIMAL(5,2),
    Remote_Status VARCHAR(50),
    Business_Travel VARCHAR(50),
    Absence_Days INT,
    Attrition VARCHAR(10),
    Hire_Date DATE,
    Exit_Date DATE
);
